os: linux
language: node_js
node_js: 12
jobs:
  include:
    - name: "Classic build"
      script: npm run build:gh
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: build
        on:
          branch: master
    - name: "ipfs build"
      install:
        - npm ci
        - npm install -g ipfs-deploy
      script: npm run build:ipfs
      deploy:
        provider: script
        script: bash scripts/deploy_ipfs.sh infura mainnet.infura.io/v3/$INFURA_ID
